development:
  adapter: postgresql
  database: hinman_development
  username: Andrew
  host: localhost
  encoding: UTF8
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: hinman_test
  username: Andrew
  host: localhost
  encoding: UTF8
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: hinman_production
  username: Andrew
  host: localhost
  encoding: UTF8
  pool: 5
  timeout: 5000